[package]
name = "arkd-rpc-client"
version = "0.0.0"
license = "CC0-1.0"
authors = [ "Steven Roose <steven@roose.io>" ]
edition = "2021"

[dependencies]

prost.workspace = true
tonic.workspace = true
tokio.workspace = true
